{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "eks-hybrid-nodes-gateway.namespace" . }}
  labels:
    {{- include "eks-hybrid-nodes-gateway.labels" . | nindent 4 }}
{{- end }}
