apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-hybrid-nodes-gateway.serviceAccountName" . }}
  namespace: {{ include "eks-hybrid-nodes-gateway.namespace" . }}
  labels:
    {{- include "eks-hybrid-nodes-gateway.labels" . | nindent 4 }}
